name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Install Tools
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Run Linter
      run: golangci-lint run

    - name: Static Analysis
      run: go vet ./...

    - name: Security Check
      run: gosec ./...

    - name: Vulnerability Scan
      run: govulncheck ./...

    - name: Run Tests
      run: go test -v -cover ./...
